os:
  - linux
  - osx

language: c++

#addons:
#  apt:
#    packages:
#      - gdb

arch:
#  - amd64
  - arm64
#  - ppc64le
#  - s390x

compiler:
#  - g++
  - clang

install: skip

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
#  - gdb --ex=r -return-child-result -batch -ex bt --args ./diamond test
#  - lldb --batch --one-line r --one-line-on-crash bt -- ./diamond test
  - ./diamond test